-- https://www.hackerrank.com/challenges/interviews/problem?isFullScreen=true&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen
SELECT C.CONTEST_ID, C.HACKER_ID, C.NAME, 
    SUM(S.TOTAL_SUBMISSIONS) AS T1, 
    SUM(S.TOTAL_ACCEPTED_SUBMISSIONS) AS T2, 
    SUM(V.TOTAL_VIEWS) AS T3, 
    SUM(V.TOTAL_UNIQUE_VIEWS) AS T4
FROM CONTESTS AS C
JOIN COLLEGES AS COL ON COL.CONTEST_ID=C.CONTEST_ID
JOIN CHALLENGES AS CHA ON CHA.COLLEGE_ID=COL.COLLEGE_ID
LEFT JOIN (
    SELECT CHALLENGE_ID, 
        SUM(TOTAL_VIEWS) AS TOTAL_VIEWS, 
        SUM(TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
    FROM VIEW_STATS
    GROUP BY CHALLENGE_ID
) AS V ON V.CHALLENGE_ID=CHA.CHALLENGE_ID
LEFT JOIN (
    SELECT CHALLENGE_ID, 
        SUM(TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS, 
        SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS
    FROM SUBMISSION_STATS
    GROUP BY CHALLENGE_ID
) AS S ON S.CHALLENGE_ID=CHA.CHALLENGE_ID
GROUP BY C.CONTEST_ID, C.HACKER_ID, C.NAME
HAVING T1 + T2 + T3 + T4 > 0
ORDER BY C.CONTEST_ID;

